// list-modification-apps/list-mods-react/src/components/ListItem.tsx
import React from 'react';
import './ListItem.css';

export interface Item {
  id: number;
  text: string;
  header: string;
}

interface Props {
  item: Item;
}

export const ListItem = ({ item }: Props) => (
  <div className="root">
    <div className="id-container">{item.id}</div>
    <div>
      <div>{item.header}</div>
      <div>{item.text}</div>
    </div>
  </div>
);

// list-modification-apps/list-mods-angular/src/app/components/ListItem/ListItem.component.ts
import { Component, Input } from "@angular/core";
import { Item } from "src/app/domain/item";

@Component({
  selector: 'app-list-item',
  template: `
  <div class="root">
    <div class="id-container">{{ item.id }}</div>
    <div>
      <div>{{ item.header }}</div>
      <div>{{ item.text }}</div>
    </div>
  </div>
  `,
  styleUrls: ['ListItem.component.css']
})
export class ListItemComponent {
  constructor() {};

  @Input()
  public item: Item;
}
