// tournament-form-apps/tournament-form-angular/src/app/pages/tournaments/apply-form/apply-form.component.ts
import { Component } from "@angular/core";
import { FormArray, FormControl, FormGroup, Validators, ValidationErrors } from "@angular/forms";
import { Store } from "@ngrx/store";
import { AppState } from "src/app/store/reducers";
import { selectTournament } from "src/app/store/tournaments/tournaments.actions";
import { CustomValidators } from "./date-validators";

const currentDate = new Date().toISOString().slice(0, 10);

const blankParticipant = {
  name: '',
  email: '',
  dateOfBirth: currentDate,
}

const teamNameValidators = [
  Validators.required,
  Validators.maxLength(20),
];

const teamShortcutValidators = [
  Validators.required,
  Validators.minLength(2),
  Validators.maxLength(3),
];

const nameValidators = [
  Validators.required,
];

const emailValidators = [
  Validators.email,
  Validators.required,
];

const dateValidators = [
  CustomValidators.dateBetween('01-01-1900', currentDate)
]

@Component({
  template: `
    <div class="form-cover">
      <div class="form-container">
        <form [formGroup]="formGroup" (submit)="this.submitForm()">
          <div class="field-container">
            <label for="teamName">Team name</label>
            <input id="teamName" type="text" formControlName="teamName" />
            <div
              *ngIf="
              formGroup.controls['teamName'].invalid && 
              (formGroup.controls['teamName'].dirty || formGroup.controls['teamName'].touched)" 
              class="error-message">
              {{getTeamNameValidationMessage(formGroup.controls['teamName'].errors)}}
            </div>
          </div>

          <div class="field-container">
            <label for="teamShortcut">Team shortcut</label>
            <input id="teamShortcut" type="text" formControlName="teamShortcut" />
            <div
              *ngIf="
              formGroup.controls['teamShortcut'].invalid && 
              (formGroup.controls['teamShortcut'].dirty || formGroup.controls['teamShortcut'].touched)" 
              class="error-message">
              {{getTeamShortcutValidationMessage(formGroup.controls['teamShortcut'].errors)}}
            </div>
          </div>

          <div 
            formArrayName="participants" 
            class="participants-holder"
          >
            <header>
              <div>
                Participants
              </div>
              <button
                type="button"
                class="primary"
                (click)="this.addNewParticipant()"
              >
                Add participant
              </button>
            </header>
            <div
              class="participant-container"
              *ngFor="let participantControl of this.participantControls; index as i"
              [formGroupName]="i"
            >
              <div class="field-container">
                <label for="name">Name</label>
                <input id="name" type="text" formControlName="name" />
                <div
                  *ngIf="
                  participantControl.controls['name'].invalid && 
                  (participantControl.controls['name'].dirty || participantControl.controls['name'].touched)" 
                  class="error-message">
                  {{getNameValidationMessage(participantControl.controls['name'].errors)}}
                </div>
              </div>
              
              <div class="field-container">
                <label for="email">E-mail</label>
                <input id="email" type="text" formControlName="email" />
                <div
                  *ngIf="
                  participantControl.controls['email'].invalid && 
                  (participantControl.controls['email'].dirty || participantControl.controls['email'].touched)" 
                  class="error-message">
                  {{getEmailValidationMessage(participantControl.controls['email'].errors)}}
                </div>
              </div>

              <div class="field-container">
                <label for="dateOfBirth">Date of birth</label>
                <input id="dateOfBirth" type="date" formControlName="dateOfBirth" />
                <div
                  *ngIf="
                  participantControl.controls['dateOfBirth'].invalid && 
                  (participantControl.controls['dateOfBirth'].dirty || participantControl.controls['dateOfBirth'].touched)" 
                  class="error-message">
                  {{getDateValidationMessage(participantControl.controls['dateOfBirth'].errors)}}
                </div>
              </div>

              <div>
                <button 
                  type="button" 
                  (click)="this.removeParticipant(i)"
                  class="secondary"
                >
                  Remove
                </button>
              </div>
            </div>
          </div>

          <div class="button-container">
            <button type="submit" class="primary">Submit</button>
            <button type="button" class="secondary" (click)="this.deselectTournament()">Cancel</button>
          </div>
        </form>
      </div>
    </div>
  `,
  styleUrls: ['./apply-form.component.scss'],
  selector: 'app-apply-form'
})
export class ApplyFormComponent {
  formGroup = new FormGroup({
    teamName: new FormControl('', teamNameValidators),
    teamShortcut: new FormControl('', teamShortcutValidators),
    participants: new FormArray([
      new FormGroup({
        name: new FormControl(blankParticipant.name, nameValidators),
        email: new FormControl(blankParticipant.email, emailValidators),
        dateOfBirth: new FormControl(blankParticipant.dateOfBirth, dateValidators),
      })
    ])
  });

  constructor(private store: Store<AppState>) {}

  submitForm() {
    console.log(this.participants.controls.forEach((control) => console.log(control.errors)));
  }

  addNewParticipant() {
    const participantControls = new FormGroup({
      name: new FormControl(blankParticipant.name),
      email: new FormControl(blankParticipant.email),
      dateOfBirth: new FormControl(blankParticipant.dateOfBirth),
    });

    this.participants.push(participantControls);
  }

  get participants() {
    return this.formGroup.controls["participants"] as FormArray;
  }

  get participantControls() {
    return this.participants.controls as FormGroup[];
  }

  removeParticipant(i: number) {
    this.participants.removeAt(i);
  }

  deselectTournament() {
    this.store.dispatch(selectTournament({}))
  }

  getTeamNameValidationMessage = (errors: ValidationErrors | null): string | undefined => {
    if (!errors) return;
    if (errors['required']) return 'Required';
    if (errors['maxlength']) return `Must be ${errors['maxlength'].requiredLength} letters or less`;
    return;
  }

  getTeamShortcutValidationMessage = (errors: ValidationErrors | null): string | undefined => {
    if (!errors) return;
    if (errors['required']) return 'Required';
    if (errors['maxlength'] || errors['minlength']) return 'Must contain 2 or 3 letters/digits';
    return;
  }

  getNameValidationMessage = (errors: ValidationErrors | null): string | undefined => {
    if (!errors) return;
    if (errors['required']) return 'Required';
    return;
  }

  getEmailValidationMessage = (errors: ValidationErrors | null): string | undefined => {
    if (!errors) return;
    if (errors['required']) return 'Required';
    if (errors['email']) return 'Field should contain valid e-mail address';
    return;
  }

  getDateValidationMessage = (errors: ValidationErrors | null): string | undefined => {
    if (!errors) return;
    if (errors['minDate']) return `Date cannot be earlier than January 1st, 1900`;
    if (errors['maxDate']) return `Date cannot come from the future`;
    return
  }
}

// tournament-form-apps/tournament-form-vue/src/components/ApplyForm.vue
<script setup>
import { Field, Form, ErrorMessage, FieldArray } from 'vee-validate';
import { useTournaments } from '@/store/tournamentsStore';
import * as Yup from 'yup';

const blankParticipant = {
  name: '',
  email: '',
  dateOfBirth: new Date().toISOString().slice(0, 10),
}

const initialValues = {
  teamName: '',
  teamShortcut: '',
  participants: [{
    ...blankParticipant
  }],
}

const schema = Yup.object({
  teamName: Yup.string()
    .required('Required')
    .max(20, 'Must be 20 letters or less'),
  teamShortcut: Yup.string()
    .required('Required')
    .min(2, 'Must contain 2 or 3 letters/digits')
    .max(3, 'Must contain 2 or 3 letters/digits'),
  participants: Yup.array().of(Yup.object({
    name: Yup.string()
      .required('Required'),
    email: Yup.string()
      .email('Field should contain valid e-mail address')
      .required('Required'),
    dateOfBirth: Yup.date()
      .min('01-01-1900', 'Date cannot be earlier than January 1st, 1900')
      .max(new Date(), 'Date cannot come from the future')
  }))
})

const state = useTournaments();
</script>

<template>
  <div class="form-cover">
    <div class="form-container">
      <Form :validation-schema="schema" :initial-values="initialValues">
        <div class="field-container">
          <label for="teamName">Team name</label>
          <Field name="teamName" type="text" />
          <ErrorMessage name="teamName" class="error-message" />
        </div>

        <div class="field-container">
          <label for="teamShortcut">Team shortcut</label>
          <Field name="teamShortcut" type="text" />
          <ErrorMessage name="teamShortcut" class="error-message" />
        </div>

        <FieldArray name="participants" v-slot="{ fields, push, remove }">
          <div class="participants-holder">
            <header>
              <div>
                Participants
              </div>
              <button type="button" class="primary" @click="push({...blankParticipant})">
                Add participant
              </button>
            </header>
            <div v-for="(_, idx) in fields" :key="idx" class="participant-container">
              <div class="field-container">
                <label :for="`participants[${idx}].name`">Name</label>
                <Field :name="`participants[${idx}].name`" type="text" />
                <ErrorMessage :name="`participants[${idx}].name`" class="error-message" />
              </div>

              <div class="field-container">
                <label :for="`participants[${idx}].email`">E-mail</label>
                <Field :name="`participants[${idx}].email`" type="email" />
                <ErrorMessage :name="`participants[${idx}].email`" class="error-message" />
              </div>

              <div class="field-container">
                <label :for="`participants[${idx}].dateOfBirth`">Date of birth</label>
                <Field :name="`participants[${idx}].dateOfBirth`" type="date" />
                <ErrorMessage :name="`participants[${idx}].dateOfBirth`" class="error-message" />
              </div>

              <div>
                <button type="button" @click="remove(idx)" class="secondary">
                  Remove
                </button>
              </div>
            </div>
          </div>
        </FieldArray>

        <div class="button-container">
          <button type="submit" class="primary">Submit</button>
          <button type="button" class="secondary" @click="state.selectTournament(undefined)">Cancel</button>
        </div>
      </Form>
    </div>
  </div>
</template>

<style lang="scss">
.form-cover {
  position: fixed;
  display: flex;
  align-items: center;
  justify-content: center;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  background-color: rgba(100, 100, 100, 0.75);
}

.form-container {
  background-color: white;
  border-radius: 10px;
  min-width: 700px;
  padding: 20px;
}

.field-container {
  display: flex;
  flex-direction: column;
}

.participants-holder {
  padding: 20px 0;
}

.participant-container {
  display: grid;
  grid-template-columns: 1fr 1fr;
  align-items: center;
  grid-template-rows: 1fr 1fr;
  border-bottom: 1px solid #ccc;
  padding-bottom: 10px;
  margin-bottom: 10px;
}

.error-message {
  color: red;
  font-size: 0.7em;
}

header {
  display: flex;
  justify-content: space-between;
}

button {
  all: unset;
  user-select: none;
  cursor: pointer;

  &.primary {
    padding: 8px 15px;
    border-radius: 6px;
    background-color: #00a;
    color: white;

    &:hover {
      background-color: #39f;
      color: white;
    }

    &:active {
      background-color: #6cf;
      color: white;
    }
  }

  &.secondary {
    color: #00a;

    &:hover {
      color: #39f;
    }

    &:active {
      color: #6cf;
    }
  }
}

input {
  padding: 6px;
  width: calc(min(300px, 100%));
}

.button-container {
  display: flex;
  gap: 10px;
}
</style>
